### ISSUE TITLE
Create/update Packages files

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/debian-adapter#11]
We need to create/update Packages.gz when deb package is added to the repository.  
Check the repo structure [here](https://www.debian.org/doc/manuals/repository-howto/repository-howto#id442666) and Packages format [here](https://wiki.debian.org/DebianRepository/Format#A.22Packages.22_Indices)

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#66](https://github.com/artipie/debian-adapter/issues/66) is solved here.
