### ISSUE TITLE
Batch-update of multiple packages

### ISSUE THREAD

**Issue by g4s8** [artipie/debian-adapter#51]
The user of debian-adapter should be able to update index files for multiple Debian packages. 
1.	Update `Packages` index file with information of the given `.deb` packages. To be more specific, the method will accept the keys (paths) list of the `.deb` packages and a key (paths) of the `Packages` index (gz-compressed).
2.	Generate or update `Release` index and `Release.gpg` file, two variants:
a)	With given `Packages` index file (after 1) we know exactly what `Packages` file was changes, so it’s faster to update/add info about this `Packages` file than to generate info about all `Packages` indexes of the repository)
b)	Without given `Packages` index file, the method will create ` Release` index and add info about all existing `Packages` indexes
3.	Generate and sign with gpg `InRelease` index file by provided `Release` index file

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4`

**Comment by olenagerasimova** [comment]
done
